const image1 = require('~/assets/images/item1.png');
const image2 = require('~/assets/images/item2.png');
const image3 = require('~/assets/images/item3.png');
const image4 = require('~/assets/images/item4.png');
const image5 = require('~/assets/images/item5.png');
const image6 = require('~/assets/images/item6.png');
const image7 = require('~/assets/images/item7.png');
const image8 = require('~/assets/images/item8.png');

const ProductItem = [
    {
        id: 1,
        img: image1,
        gender: 'female',
        categorySlug: 'ao-thun',
        slug: 'ao-thun-nu-1',
        title: 'Plain White Shirt',
        price: 29.0,
        old_price: 39.0,
        colors: ['white', 'black', 'blue', 'red'],
        size: ['S', 'M', 'L', 'XL'],
    },
    {
        id: 2,
        img: image2,
        gender: 'female',
        categorySlug: 'ao-khoac',
        slug: 'ao-khoac-nu-1',
        title: 'Denim Jacket ',
        price: 69.0,
        old_price: 89.0,
        colors: ['blue', 'black'],
        size: ['L', 'XL'],
    },
    {
        id: 3,
        img: image3,
        gender: 'female',
        categorySlug: 'ao-polo',
        slug: 'ao-polo-nu-1',
        title: 'Black Polo Shirt',
        price: 49.0,
        old_price: 59.0,
        colors: ['white', 'black', 'blue', 'red', 'pink'],
        size: ['S', 'M', 'L', 'XL'],
    },
    {
        id: 4,
        img: image4,
        gender: 'female',
        categorySlug: 'ao-hoodie',
        slug: 'ao-hoodie-nu-1',
        title: 'Blue Sweatshirt',
        price: 79.0,
        old_price: 109.0,
        colors: ['white', 'black', 'blue', 'red', 'yellow'],
        size: ['M', 'L', 'XL'],
    },
    {
        id: 5,
        img: image5,
        gender: 'male',
        categorySlug: 'ao-somi',
        slug: 'ao-somi-nam-1',
        title: 'Blue Plain Shirt',
        price: 49.0,
        old_price: 69.0,
        colors: ['white', 'black', 'blue'],
        size: ['S', 'M', 'L', 'XL'],
    },
    {
        id: 6,
        img: image6,
        gender: 'male',
        categorySlug: 'ao-somi',
        slug: 'ao-somi-nam-2',
        title: 'Dark Blue Shirt',
        price: 89.0,
        old_price: 129.0,
        colors: ['white', 'black', 'blue'],
        size: ['S', 'M', 'L', 'XL'],
    },
    {
        id: 7,
        img: image7,
        gender: 'male',
        categorySlug: 'ao-thun',
        slug: 'ao-thun-nam-1',
        title: 'Outcast T Shirt',
        price: 19.0,
        old_price: 39.0,
        colors: ['white', 'black', 'blue'],
        size: ['S', 'M', 'L', 'XL'],
    },
    {
        id: 8,
        img: image8,
        gender: 'male',
        categorySlug: 'ao-polo',
        slug: 'ao-polo-nam-1',
        title: 'Polo Plain Shirt',
        price: 29.0,
        old_price: 39.0,
        colors: ['white', 'black', 'blue', 'red', 'yellow'],
        size: ['S', 'M', 'L', 'XL'],
    },
    // {
    //     id: 9,
    //     img: image1,
    //     gender: ['female'],
    //     categorySlug: 'ao-thun',
    //     slug: 'ao-thun-nu',
    //     title: 'Plain White Shirt',
    //     price: 29.0,
    //     colors: ['white', 'black', 'blue', 'red'],
    //     size: ['s', 'm', 'l', 'xl'],
    // },
    // {
    //     id: 10,
    //     img: image2,
    //     gender: ['female'],
    //     categorySlug: 'ao-khoac',
    //     slug: 'ao-khoac-nu',
    //     title: 'Denim Jacket ',
    //     price: 69.0,
    //     colors: ['blue', 'black'],
    //     size: ['l', 'xl'],
    // },
    // {
    //     id: 11,
    //     img: image3,
    //     gender: ['female'],
    //     categorySlug: 'ao-polo',
    //     slug: 'ao-polo-nu',
    //     title: 'Black Polo Shirt',
    //     price: 49.0,
    //     colors: ['white', 'black', 'blue', 'red', 'pink'],
    //     size: ['s', 'm', 'l', 'xl'],
    // },
    // {
    //     id: 12,
    //     img: image4,
    //     gender: ['female'],
    //     categorySlug: 'ao-hoodie',
    //     slug: 'ao-hoodie-nu',
    //     title: 'Blue Sweatshirt',
    //     price: 79.0,
    //     colors: ['white', 'black', 'blue', 'red', 'yellow'],
    //     size: ['m', 'l', 'xl'],
    // },
    // {
    //     id: 13,
    //     img: image5,
    //     gender: ['male'],
    //     categorySlug: 'ao-somi',
    //     slug: 'ao-somi-nam',
    //     title: 'Blue Plain Shirt',
    //     price: 49.0,
    //     colors: ['white', 'black', 'blue'],
    //     size: ['s', 'm', 'l', 'xl'],
    // },
    // {
    //     id: 14,
    //     img: image6,
    //     gender: ['male'],
    //     categorySlug: 'ao-somi',
    //     slug: 'ao-somi-nam',
    //     title: 'Dark Blue Shirt',
    //     price: 89.0,
    //     colors: ['white', 'black', 'blue'],
    //     size: ['s', 'm', 'l', 'xl'],
    // },
    // {
    //     id: 15,
    //     img: image7,
    //     gender: ['male'],
    //     categorySlug: 'ao-thun',
    //     slug: 'ao-thun-nam',
    //     title: 'Outcast T Shirt',
    //     price: 19.0,
    //     colors: ['white', 'black', 'blue'],
    //     size: ['s', 'm', 'l', 'xl'],
    // },
    // {
    //     id: 16,
    //     img: image8,
    //     gender: ['male'],
    //     categorySlug: 'ao-polo',
    //     slug: 'ao-polo-nam',
    //     title: 'Polo Plain Shirt',
    //     price: 29.0,
    //     colors: ['white', 'black', 'blue', 'red', 'yellow'],
    //     size: ['s', 'm', 'l', 'xl'],
    // },
    // {
    //     id: 17,
    //     img: image1,
    //     gender: ['female'],
    //     categorySlug: 'ao-thun',
    //     slug: 'ao-thun-nu',
    //     title: 'Plain White Shirt',
    //     price: 29.0,
    //     colors: ['white', 'black', 'blue', 'red'],
    //     size: ['s', 'm', 'l', 'xl'],
    // },
    // {
    //     id: 18,
    //     img: image2,
    //     gender: ['female'],
    //     categorySlug: 'ao-khoac',
    //     slug: 'ao-khoac-nu',
    //     title: 'Denim Jacket ',
    //     price: 69.0,
    //     colors: ['blue', 'black'],
    //     size: ['l', 'xl'],
    // },
    // {
    //     id: 19,
    //     img: image3,
    //     gender: ['female'],
    //     categorySlug: 'ao-polo',
    //     slug: 'ao-polo-nu',
    //     title: 'Black Polo Shirt',
    //     price: 49.0,
    //     colors: ['white', 'black', 'blue', 'red', 'pink'],
    //     size: ['s', 'm', 'l', 'xl'],
    // },
    // {
    //     id: 20,
    //     img: image4,
    //     gender: ['female'],
    //     categorySlug: 'ao-hoodie',
    //     slug: 'ao-hoodie-nu',
    //     title: 'Blue Sweatshirt',
    //     price: 79.0,
    //     colors: ['white', 'black', 'blue', 'red', 'yellow'],
    //     size: ['m', 'l', 'xl'],
    // },
    // {
    //     id: 21,
    //     img: image5,
    //     gender: ['male'],
    //     categorySlug: 'ao-somi',
    //     slug: 'ao-somi-nam',
    //     title: 'Blue Plain Shirt',
    //     price: 49.0,
    //     colors: ['white', 'black', 'blue'],
    //     size: ['s', 'm', 'l', 'xl'],
    // },
    // {
    //     id: 22,
    //     img: image6,
    //     gender: ['male'],
    //     categorySlug: 'ao-somi',
    //     slug: 'ao-somi-nam',
    //     title: 'Dark Blue Shirt',
    //     price: 89.0,
    //     colors: ['white', 'black', 'blue'],
    //     size: ['s', 'm', 'l', 'xl'],
    // },
    // {
    //     id: 23,
    //     img: image7,
    //     gender: ['male'],
    //     categorySlug: 'ao-thun',
    //     slug: 'ao-thun-nam',
    //     title: 'Outcast T Shirt',
    //     price: 19.0,
    //     colors: ['white', 'black', 'blue'],
    //     size: ['s', 'm', 'l', 'xl'],
    // },
    // {
    //     id: 24,
    //     img: image8,
    //     gender: ['male'],
    //     categorySlug: 'ao-polo',
    //     slug: 'ao-polo-nam',
    //     title: 'Polo Plain Shirt',
    //     price: 29.0,
    //     colors: ['white', 'black', 'blue', 'red', 'yellow'],
    //     size: ['s', 'm', 'l', 'xl'],
    // },
    // {
    //     id: 25,
    //     img: image1,
    //     gender: ['female'],
    //     categorySlug: 'ao-thun',
    //     slug: 'ao-thun-nu',
    //     title: 'Plain White Shirt',
    //     price: 29.0,
    //     colors: ['white', 'black', 'blue', 'red'],
    //     size: ['s', 'm', 'l', 'xl'],
    // },
    // {
    //     id: 26,
    //     img: image2,
    //     gender: ['female'],
    //     categorySlug: 'ao-khoac',
    //     slug: 'ao-khoac-nu',
    //     title: 'Denim Jacket ',
    //     price: 69.0,
    //     colors: ['blue', 'black'],
    //     size: ['l', 'xl'],
    // },
    // {
    //     id: 27,
    //     img: image3,
    //     gender: ['female'],
    //     categorySlug: 'ao-polo',
    //     slug: 'ao-polo-nu',
    //     title: 'Black Polo Shirt',
    //     price: 49.0,
    //     colors: ['white', 'black', 'blue', 'red', 'pink'],
    //     size: ['s', 'm', 'l', 'xl'],
    // },
    // {
    //     id: 28,
    //     img: image4,
    //     gender: ['female'],
    //     categorySlug: 'ao-hoodie',
    //     slug: 'ao-hoodie-nu',
    //     title: 'Blue Sweatshirt',
    //     price: 79.0,
    //     colors: ['white', 'black', 'blue', 'red', 'yellow'],
    //     size: ['m', 'l', 'xl'],
    // },
    // {
    //     id: 29,
    //     img: image5,
    //     gender: ['male'],
    //     categorySlug: 'ao-somi',
    //     slug: 'ao-somi-nam',
    //     title: 'Blue Plain Shirt',
    //     price: 49.0,
    //     colors: ['white', 'black', 'blue'],
    //     size: ['s', 'm', 'l', 'xl'],
    // },
    // {
    //     id: 30,
    //     img: image6,
    //     gender: ['male'],
    //     categorySlug: 'ao-somi',
    //     slug: 'ao-somi-nam',
    //     title: 'Dark Blue Shirt',
    //     price: 89.0,
    //     colors: ['white', 'black', 'blue'],
    //     size: ['s', 'm', 'l', 'xl'],
    // },
    // {
    //     id: 31,
    //     img: image7,
    //     gender: ['male'],
    //     categorySlug: 'ao-thun',
    //     slug: 'ao-thun-nam',
    //     title: 'Outcast T Shirt',
    //     price: 19.0,
    //     colors: ['white', 'black', 'blue'],
    //     size: ['s', 'm', 'l', 'xl'],
    // },
    // {
    //     id: 32,
    //     img: image8,
    //     gender: ['male'],
    //     categorySlug: 'ao-polo',
    //     slug: 'ao-polo-nam',
    //     title: 'Polo Plain Shirt',
    //     price: 29.0,
    //     colors: ['white', 'black', 'blue', 'red', 'yellow'],
    //     size: ['s', 'm', 'l', 'xl'],
    // },
];

const getProductBySlug = (slug) => ProductItem.find((e) => e.slug === slug);

const getCartItemsDetails = (cartItems) => {
    let res = [];
    if (cartItems.length > 0) {
        cartItems.forEach((e) => {
            res.push({
                ...e,
                product: getProductBySlug(e.slug),
            });
        });
    }
    return res;
};

const ProductData = {
    ProductItem,
    getProductBySlug,
    getCartItemsDetails,
};

export default ProductData;
